Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Bayesian Ridge Regression
from sklearn import linear_model
clf = linear_model.BayesianRidge()
pred_test_bayesian_ridge = clf.fit(training, training_label).predict(test)

# data asli
denormalized_data_test_bayesian_ridge = pd.DataFrame(scaler.inverse_transform(test_label),columns=["Testing Data"])
denormalized_data_test_bayesian_ridge = scaler.fit_transform(denormalized_data_test)
denormalized_data_test_bayesian_ridge = pd.DataFrame(scaler.inverse_transform(test_label),columns=["Testing Data"])
# data prediksi
denormalized_data_preds_bayesian_ridge = pd.DataFrame(scaler.inverse_transform(pred_test_bayesian_ridge.reshape(-1, 1)),columns=["Predict Data"])

MSE_bayesian_ridge = abs(mean_squared_error(test_label,pred_test_bayesian_ridge))
MAPE_bayesian_ridge = mean_absolute_percentage_error(denormalized_data_test_bayesian_ridge, denormalized_data_preds_bayesian_ridge)
# MAE_bayesian_ridge = mean_absolute_error(denormalized_data_test_bayesian_ridge,denormalized_data_preds_bayesian_ridge)
------------------

----- stderr -----
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
------------------

[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-24-d9f94fd7214e>[0m in [0;36m<cell line: 13>[0;34m()[0m
[1;32m     11[0m [0mdenormalized_data_preds_bayesian_ridge[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mscaler[0m[0;34m.[0m[0minverse_transform[0m[0;34m([0m[0mpred_test_bayesian_ridge[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0;34m-[0m[0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m)[0m[0;34m)[0m[0;34m,[0m[0mcolumns[0m[0;34m=[0m[0;34m[[0m[0;34m"Predict Data"[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;34m[0m[0m
[0;32m---> 13[0;31m [0mMSE_bayesian_ridge[0m [0;34m=[0m [0mabs[0m[0;34m([0m[0mmean_squared_error[0m[0;34m([0m[0mtest_label[0m[0;34m,[0m[0mpred_test_bayesian_ridge[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m [0mMAPE_bayesian_ridge[0m [0;34m=[0m [0mmean_absolute_percentage_error[0m[0;34m([0m[0mdenormalized_data_test_bayesian_ridge[0m[0;34m,[0m [0mdenormalized_data_preds_bayesian_ridge[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m [0;31m# MAE_bayesian_ridge = mean_absolute_error(denormalized_data_test_bayesian_ridge,denormalized_data_preds_bayesian_ridge)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'mean_squared_error' is not defined

